### ISSUE TITLE
Script crashes when NoneType value passed to UpdateSQL.

### ISSUE THREAD

**Issue by MorganFellDEV** [MorganFellDEV/HowMuchIsAFreddo#1]
No error checking for NoneType values, provided when hmiaf-scrape is unable to return a result (typically from a dead link or a time-out).

`Traceback (most recent call last):
  File "/home/ec2-user/HowMuchIsAFreddo/hmiaf-scrape/scraperMain.py", line 107, in <module>
    start_scraper()
  File "/home/ec2-user/HowMuchIsAFreddo/hmiaf-scrape/scraperMain.py", line 57, in start_scraper
    if (price_sql != float(price_scrape)):
TypeError: float() argument must be a string or a number, not 'NoneType'`

**Comment by MorganFellDEV** [comment]
Fixed in d8ac923. 

Needs better handling for the exception in the scraper but for now it will do.
